### ISSUE TITLE
Was this only for hack day or would you welcome contributions?

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmpeg-amia-wiki#1]
^^
Seems like this could be a good resource for archivists. I see that he ffmpeg scripts section was left unfinished as well.

Best,

Kieran,
Irish Film Archive.

**Comment by ablwr** [comment]
Always welcome contributions!

**Comment by kieranjol** [comment]
Thanks for getting back so quick!
Just a quick question. Does the wiki require pull requests/merging or are all edits immediately viewable? I'd almost prefer the former as I'm not sure if what I have to offer would be useful.

**Comment by dericed** [comment]
Oh, I always figured this repo was just an ffmpeg fork. Perhaps it should be renamed.

**Comment by dericed** [comment]
Keep in mind there's also the [ffmpeg wiki](http://trac.ffmpeg.org/) which already has a little documentation for archivists.

**Comment by ablwr** [comment]
I support renaming this. Also think it'd work better not in a wiki format.

**Comment by retokromer** [comment]
I my opinion, we should update, and possibly re-order and/or integrate into ffmprovisr, or [you name it] this resource. Or, at least, mark it as outdated.

**Comment by dericed** [comment]
i renamed the repo as well.

**Comment by retokromer** [comment]
I close this.
